### ISSUE TITLE
where is car_img

### ISSUE THREAD

**Issue by MobiusLeo** [cnzzx/GeMap#10]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/home/lixiang/lijixiang/GeMap/figs/lidar_car.png'
  File "/home/lixiang/lijixiang/GeMap/tools/gemap/vis_pred.py", line 199, in main
    car_img = Image.open('./figs/lidar_car.png')
  File "/home/lixiang/lijixiang/GeMap/tools/gemap/vis_pred.py", line 393, in <module>
    main()
FileNotFoundError: [Errno 2] No such file or directory: '/home/lixiang/lijixiang/GeMap/figs/lidar_car.png'

**Comment by cnzzx** [comment]
Sorry that there are some figures missed for visualization. Now the missed figures are uploaded. Thanks for your interest!
