### ISSUE TITLE
What's the meaning of simple and full of objects?

### ISSUE THREAD

**Issue by MobiusLeo** [cnzzx/GeMap#11]
Hi, I have a question that I don't know about the meaning of simple and full of objects. This appears in your "Quantitative Results" sections of GitHub page. In fact, I test the different model which belong to the simple or full objects, I have a doubtful conclusion that in the simple objects model the GeMap network only detect the common objects which same as nuscenes, but in full objects model, besides the the common objects we also detects the map node that is our true goal. Is it right? Thank you!

**Comment by cnzzx** [comment]
Thanks for your interest! The difference between "simple" and "full" objectives is the loss function (not object sets). 
- In the "simple" version, we only train the model with point-to-point, edge, classification, and geometry losses. This is a clearer setting to analyze the effect of our proposed method. 
- To get more powerful models, in the "full" objective configuration, we add extra dense prediction losses, including Persepctive-View segmentation, Bird's-Eye-View segmentation, and depth estimation (to support depth estimation better, the feature extraction module is slightly different, where LSS is adopted). More details can be found in the appendix of [our paper](https://arxiv.org/abs/2312.03341).
