### ISSUE TITLE
Which BEV encoder is better, GKT or LSS?

### ISSUE THREAD

**Issue by QixingJiang** [cnzzx/GeMap#16]
Dear author,
    Thanks for your excellent work. I have a question about the BEV encoder. In MapTR(v1), the author choosed GKT as their BEVEncoder. The benchmark [benchmark](https://github.com/hustvl/MapTR?tab=readme-ov-file#maptr)shows LSS (bevpool) and GKT have almost the same performance.
![Snipaste_2024-08-14_15-08-22](https://github.com/user-attachments/assets/c459e41e-ec13-4d02-96be-96f71e7e56c2)
However,  in MapTRv2 the author choosed LSS as their BEVEncoder, while the a table in the Maptrv2 paper shows LSS is not better. The author explained in an issue that "Bevpool can explicitly utilize the depth information and significantly boost the performance.". https://github.com/hustvl/MapTR/issues/114
<img width="452" alt="image" src="https://github.com/user-attachments/assets/34d3fc25-462e-4919-af65-41f474f0b3af">
    So I wonder if you have tried comparing the performance differences between LSS and GKT in GeMap, and why you chose GKT as the BEV encoder (compared to LSS). Additionally, in my opinion, when depth information is removed, GKT is not as good as LSS, especially when CAN bus-related information is removed. LSS cannot operate, but GKT can still have some effect. Is this a right view?

**Comment by cnzzx** [comment]
Thanks for your interest! Currently, we don't have a plan for such a comparison. This work is first done with GKT, and in order to add auxiliary supervision (depth), the transformation is changed to LSS. If not to leverage depth, in my opinion, GKT can avoid accumulated errors for depth estimation and might be a better choice.

**Comment by QixingJiang** [comment]
Thank you for your reply, it was very helpful to me.
