### ISSUE TITLE
Experiment logs

### ISSUE THREAD

**Issue by wanmeiziyoulan** [cnzzx/GeMap#17]
Could you please provide the logs of the full configuration in NuScenes and Argoverse as a reference? Looking forward to your reply. Thanks!
![image](https://github.com/user-attachments/assets/38f37842-83bf-4e90-8c2c-0da3d49f48e0)
![image](https://github.com/user-attachments/assets/d5f59bf6-6aeb-4c6b-be7f-4c249c89c39a)

**Comment by cnzzx** [comment]
Thanks for your suggestion. We've added logs for all major experiments in [this commit](https://github.com/cnzzx/GeMap/commit/844258835b405019313f5d2aa09579da0d1e1277). Now you can access them in README.
