### ISSUE TITLE
ECCV poster

### ISSUE THREAD

**Issue by m990130** [cnzzx/GeMap#19]
Hi guys, this sounds weird. Not sure what's the best way to contact you so I will write it down here. I came across your poster on the ECCV page and found that you probably forgot the "Kong" in "The Chinese University of Hong Kong" somewhere on your poster. 
<img width="481" alt="image" src="https://github.com/user-attachments/assets/b567482f-7f4f-4b47-a41c-7b0edf328e7b">

**Comment by cnzzx** [comment]
Thanks! I correct it just now.
