### ISSUE TITLE
networkx.exception.NodeNotFound: 

### ISSUE THREAD

**Issue by jasonchengf** [cnzzx/GeMap#3]
when i run python tools/gemap/custom_av2_map_converter.py --data-root ./data/hdmap/av2/sensor/ --out-dir ./data/hdmap/av2/sensor/full    
 an error message appears:
networkx.exception.NodeNotFound: target node [(1599.82, 226.695, 14.85), (1622.585, 225.45, 14.965), (1648.38, 274.055, 13.135), (1602.89, 225.295, 14.935), (1577.315, 256.68, 14.1), (1576.23, 259.925, 14.05), (1645.89, 276.635, 13.215), (1650.755, 271.665, 13.11), (1625.335, 230.325, 14.91)] not in graph
Can you help me with this one?

**Comment by cnzzx** [comment]
Thanks for your interest. I guess there might be some problem with your networkx version. We've tested this command on our device with networkx==3.1 and it worked well. You can try to update your networkx first.
