### ISSUE TITLE
Some questions about z_cfg

### ISSUE THREAD

**Issue by jasonchengf** [cnzzx/GeMap#5]
Hi, have you tried setting the pred_z_flag and gt_z_flag within z_cfg to True to train and go for evaluation of accuracy? I tried pred_z_flag and gt_z_flag within z_cfg set to True but reported an error, now I'm trying to modify the associated loss for the added z values. If you haven't done the above attempts, can you give me some advice? Really thank you very much!!!

**Comment by cnzzx** [comment]
Thanks for your interest, we haven't tried to predict the z values. To support 3D prediction, [the computing of geometric representations](https://github.com/cnzzx/GeMap/blob/72a001f7f1d30e15df9ceb51fe436538f07adecd/projects/mmdet3d_plugin/gemap/losses/geo_loss.py#L84C1-L130C37) should be modified. In our method, computing the sine value of the angle between two displacement vectors is required, which is different between 2D and 3D cases.

**Comment by jasonchengf** [comment]
Thank you so much for the advice you provided, I really appreciate it. Your insights are very valuable to me and I will seriously consider and try to apply the suggestions as much as possible. Thank you for your generosity in sharing!
