### ISSUE TITLE
Time consumption for training? 

### ISSUE THREAD

**Issue by Wolfybox** [cnzzx/GeMap#7]
Hi author, thanks for the great work.
Got a few questions: 
1. How long does it take to do full 110 epochs with 8 3090Ti？
2. What is the performance for V2-99 backbone when training for 24 epochs?

**Comment by cnzzx** [comment]
Thanks for your interest. 
1. The training time will be influenced by the backbone, but generally, it takes 1~2 days (For V2-99, we train for 2 days). 
2. Sorry that we didn't try only training the model (with V2-99) for 24 epochs.

**Comment by Wolfybox** [comment]
> Thanks for your interest.
> 
> 1. The training time will be influenced by the backbone, but generally, it takes 1~2 days (For V2-99, we train for 2 days).
> 2. Sorry that we didn't try only training the model (with V2-99) for 24 epochs.

Thank you, it is very helpful.
